# Generated by Django 4.2.3 on 2023-08-28 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisement_delete_advertisements'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='app_advertisements_advertisements',
        ),
    ]
